sudo: required
language: c

os: linux
dist: bionic

env:
  - APPS_DIR=software/apps PK=.travis/dummy.pem

install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt update
  - sudo apt install gcc-arm-embedded -y
  - sudo apt install python-setuptools python3-setuptools python python3 python3-pip python-pip -y
  - pip3 install pip --upgrade
  - pip3 install nrfutil

jobs:
  include:
    - stage: "build"
      script:
      - .travis/build_dir.sh
      - APPS_DIR=software/apps/permacam .travis/build_dir.sh
